# Generated by Django 4.0.5 on 2022-10-01 09:52

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat', models.BooleanField(default=False, verbose_name='زیر مجموعه')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='نامک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='عکس')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='home.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم')),
                ('amount', models.IntegerField(verbose_name='تعداد')),
                ('unit_price', models.IntegerField(verbose_name='قیمت واحد')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='تخفیف')),
                ('total_price', models.IntegerField(default=0, verbose_name='قیمت کل')),
                ('information', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='اطلاعات')),
                ('status', models.CharField(choices=[('None', 'هیچکدام'), ('Size', 'سایز'), ('Color', 'رنگ'), ('Both', 'هر دو')], default='None', max_length=200, verbose_name='وضعیت')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('update', models.DateTimeField(verbose_name='بروزرسانی')),
                ('available', models.BooleanField(default=True, verbose_name='موجودی')),
                ('image', models.ImageField(upload_to='product', verbose_name='عکس')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.brand', verbose_name='برند')),
                ('category', models.ManyToManyField(blank=True, related_name='cat_product', to='home.category', verbose_name='دسته بندی')),
                ('color', models.ManyToManyField(blank=True, to='home.color', verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'محصولات',
                'verbose_name_plural': 'محصول',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایز',
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('update', models.DateTimeField(verbose_name='بروزرسانی')),
                ('amount', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.PositiveIntegerField(verbose_name='قیمت واحد')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='تخفیف')),
                ('available', models.BooleanField(default=True, verbose_name='موجودی')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.color', verbose_name='رنگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr_var', to='home.product', verbose_name='محصول')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v_size', to='home.size', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'تنوع',
                'verbose_name_plural': 'تنوع',
            },
        ),
        migrations.CreateModel(
            name='UserWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(blank=True, related_name='product_favourite', to='home.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'علاقه مندی',
                'verbose_name_plural': 'علاقه مندی ها',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='s_product', to='home.size', verbose_name='سایز'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='تگ'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='image/', verbose_name='عکس')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_product', to='home.product', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('rate', models.PositiveIntegerField(default=1, verbose_name='امتیاز')),
                ('is_reply', models.BooleanField(default=False, verbose_name='ایا پاسخ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_product', to='home.product', verbose_name='محصول')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='home.comment', verbose_name='پاسخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام',
            },
        ),
    ]
